name: Update Deployment

on:
  repository_dispatch:
    types: [update-deployment]

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq -y
      - name: Get new tag
        run: |
          NEW_TAG=$(curl -s -S "https://registry.hub.docker.com/v2/repositories/rayahh/3tier-front/tags/" | jq '."results"[]["name"]' | sed -n 1p | sed -e "s/^.//;s/.$//")
          echo "::set-output name=new_tag::$NEW_TAG"
          echo $NEW_TAG
        id: get-new-tag
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update deployment manifest
        env:
          NEW_TAG: ${{ steps.get-new-tag.outputs.new_tag }}
        run: |
          echo $NEW_TAG
          echo "Before sed: $(cat k8s/client-deployment.yml)"
          sed -i "s|rayahh/3tier-front:[^[:space:]]*|rayahh/3tier-front:${NEW_TAG}|" k8s/client-deployment.yml
          echo "After sed: $(cat k8s/client-deployment.yml)"
          echo "New image tag: $NEW_TAG"
      
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/client-deployment.yml
          git commit -m "Update image tag to $NEW_TAG"
          git push
      - name: Push Changes to Infra Repo
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.INFRA_REPO_TOKEN }}
